[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1280x1024x24
autostart=true
autorestart=true
stderr_logfile=/var/log/xvfb.err.log
stdout_logfile=/var/log/xvfb.out.log

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=:99
autostart=true
autorestart=true
user=kaliuser
stderr_logfile=/var/log/fluxbox.err.log

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -nopw -listen localhost
autostart=true
autorestart=true
stderr_logfile=/var/log/x11vnc.err.log

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
autostart=true
autorestart=true
stderr_logfile=/var/log/novnc.err.log